name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - master

# We need this to be able to create releases.
permissions:
  contents: write

jobs:
  deploay:
    name: Deploy prayer times
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Push prayer times
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cargo install --git https://github.com/ibad-al-rahman/prayer-time-index-generator
          /bin/bash ./deploy.sh
